server:
  port: 8080

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  servlet:
    multipart:
      location: /Users/minz/Downloads/upload
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB


  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: INFO
    sql: ERROR
    org:
      springframework:
        security:
          web: debug
